# Generated by Django 5.0.6 on 2024-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_ID', models.CharField(max_length=11)),
                ('guide_name', models.CharField(max_length=30)),
                ('guide_last_name', models.CharField(max_length=30)),
                ('guide_mobiluri', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ID', models.CharField(max_length=11)),
                ('visitor_name', models.CharField(max_length=30)),
                ('visitor_last_name', models.CharField(max_length=30)),
                ('visitor_mobiluri', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=30)),
                ('tour_length_days', models.IntegerField()),
                ('tour_start_date', models.DateField()),
                ('tour_guide', models.ManyToManyField(to='Hello_Georgia.guides')),
            ],
        ),
    ]
