# Generated by Django 5.0.6 on 2024-07-01 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_Georgia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='chosen_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hello_Georgia.tour'),
        ),
    ]
