# Generated by Django 5.0.6 on 2024-06-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_Georgia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='chosen_tour',
            field=models.ManyToManyField(to='Hello_Georgia.tours'),
        ),
    ]
