# Generated by Django 5.0.6 on 2024-07-01 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello_Georgia', '0002_alter_visitor_chosen_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_guide',
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_guide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hello_Georgia.guide'),
        ),
    ]
